[project]
name = "dbt-bitcoin-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-core>=1.10.15",
    "dbt-snowflake>=1.10.3",
    "pandas>=2.3.3",
    "simplejson>=3.20.2",
]
